name: 哔哩哔哩签到

on:
    workflow_dispatch:
    schedule:
        - cron: "00 16 * * *"
        #- cron: "5 16 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 查看
              uses: actions/checkout@v2

            - name: "初始化Python"
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 哔哩哔哩签到"
              run: python3 bilibili.py
              env:
                  BILI_USER: ${{ secrets.BILI_USER }}
                  BILI_PASS: ${{ secrets.BILI_PASS }}

            - name:  ${{ env.CACHE_NAME }}
            #- name: 缓存 Pip 模块
              uses: actions/cache@v2
              env:
                CACHE_NAME:  缓存 Pip 模块
              with:
                # This path is specific to Ubuntu
                path: ~/.cache/pip
                # Look to see if there is a cache hit for the corresponding requirements file
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
                  ${{ runner.os }}-
#最后推送 2021年5月19日
