name: AutoTest

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '10 12 * * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Build and publish
      env: 
        QW360_TOKEN: ${{ secrets.QW360_TOKEN }}
        GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
        QQ: ${{ secrets.QQ }}
        QMSG_KEY: ${{ secrets.QMSG_KEY }}
        WOMAIL_URL: ${{ secrets.WOMAIL_URL }}
      run: |
        python3 womail.py
        python3 glados.py
        python3 pushmsg.py
